### ISSUE TITLE
docker image seems to have dependancy issues

### ISSUE THREAD

**Issue by janesmae** [alumae/kiirkirjutaja#1]
Seems that the container itselt has some missing dependancies for python. Maybe an issue with script location?

This is current debug log:
`
> docker pull koodivaramu.eesti.ee:5050/taltechnlp/kiirkirjutaja
> docker run --shm-size 2GB --name kiirkirjutaja --rm -d -t koodivaramu.eesti.ee:5050/taltechnlp/kiirkirjutaja
> docker exec -it kiirkirjutaja python3 main.py https://icecast.err.ee/vikerraadio.mp3 
Traceback (most recent call last):
  File "main.py", line 23, in <module>
    import utils
ModuleNotFoundError: No module named 'utils'
`

**Comment by alumae** [comment]
Sorry, fixed now.
