### ISSUE TITLE
Timestamp skew from local larger than 60 sec (YouTube)

### ISSUE THREAD

**Issue by MortenKoppel** [alumae/kiirkirjutaja#3]
Hello! We are receiving the following non-blocking error to kiirkirjutaja log output while POSTing captions to YouTube service. Is it because subtitles are not being posted fast enough? Is there a way to speed up the process, like allocating more CPU, GPU etc? Or we can only increase the delay in YouTube service to wait for delayed subtitles?

```
INFO:root:Response status 400 Bad Request: 2021-11-05T12:17:21.075
Timestamp skew from local=2021-11-05T12:17:21.074 larger than 60 sec in /closedcaption?cid=xxxx-xxxx-xxxx-xxxx-xxxx&seq=xxx
```

**Comment by alumae** [comment]
It's difficult to say based on this piece of information. Please send (private is OK)  much longer output prior to this error.

**Comment by MortenKoppel** [comment]
Thank you for the quick feedback. Just a thought, maybe it is taking more time because we are using radio mp3 stream with music instead of rtmp with just regular speech? https://icecast.err.ee/vikerraadio.mp3 .  More exact log output:
[snippet.txt](https://github.com/alumae/kiirkirjutaja/files/7486328/snippet.txt)

**Comment by alumae** [comment]
Are you using the latest Docker image (koodivaramu.eesti.ee:5050/taltechnlp/kiirkirjutaja:0.2.1)? I think you encountered a bug that has been already been fixed.

**Comment by MortenKoppel** [comment]
You are correct, now with latest image this problem is gone. Thank you!

P.S. Any link to changelog for the images would be nice to have.
